# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
