# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88quote', '0002_auto_20171220_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
